<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EOS.Dashboard\EOS.Dashboard.csproj" />
    <ProjectReference Include="..\EOS.Contracts\EOS.Contracts.csproj" />
  </ItemGroup>

</Project>
